### ISSUE TITLE
Erreur 404 dans le formulaire de contact

### ISSUE THREAD

**Issue by VincentTam** [nadiaprojets/porfolio1#1]
![Screenshot from 2020-08-28 09-52-53](https://user-images.githubusercontent.com/5748535/91535980-4f766b80-e914-11ea-871b-fc8e52690639.png)

**Comment by nadiaprojets** [comment]
Bonjour Vincent, merci pour ton message, effectivement le formulaire ne fonctionne pas car il n'y a aucune fonctionnalité dans ce projet car ce n'est que des projets en front-end. Pour le moment je ne fais que des interfaces web.  Je vais faire prochainement mon portfolio professionnel mais il ne sera pas hégergé sur GitHub.
